//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiquidVisions.PanthaRhei.Expanders.CleanArchitecture {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiquidVisions.PanthaRhei.Expanders.CleanArchitecture.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure.Api.
        /// </summary>
        public static string Api {
            get {
                return ResourceManager.GetString("Api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boundaries.
        /// </summary>
        public static string ApplicationBoundariesFolder {
            get {
                return ResourceManager.GetString("ApplicationBoundariesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationDependencyInjectionBootstrapperTemplate.
        /// </summary>
        public static string ApplicationDependencyInjectionBootstrapperTemplate {
            get {
                return ResourceManager.GetString("ApplicationDependencyInjectionBootstrapperTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappers.
        /// </summary>
        public static string ApplicationMapperFolder {
            get {
                return ResourceManager.GetString("ApplicationMapperFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationMapperTemplate.
        /// </summary>
        public static string ApplicationMapperTemplate {
            get {
                return ResourceManager.GetString("ApplicationMapperTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appsettings.json.
        /// </summary>
        public static string AppSettingsJson {
            get {
                return ResourceManager.GetString("AppSettingsJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BoundaryTemplate.
        /// </summary>
        public static string BoundaryTemplate {
            get {
                return ResourceManager.GetString("BoundaryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client.
        /// </summary>
        public static string Client {
            get {
                return ResourceManager.GetString("Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientTemplate.
        /// </summary>
        public static string ClientTemplate {
            get {
                return ResourceManager.GetString("ClientTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commands.
        /// </summary>
        public static string Commands {
            get {
                return ResourceManager.GetString("Commands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DbContextTemplate.
        /// </summary>
        public static string DbContextTemplate {
            get {
                return ResourceManager.GetString("DbContextTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create, Update, Get, GetById, Delete.
        /// </summary>
        public static string DefaultRequestActions {
            get {
                return ResourceManager.GetString("DefaultRequestActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DependencyInjectionBootstrapper.cs.
        /// </summary>
        public static string DependencyInjectionBootstrapperFile {
            get {
                return ResourceManager.GetString("DependencyInjectionBootstrapperFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        public static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities.
        /// </summary>
        public static string DomainEntityFolder {
            get {
                return ResourceManager.GetString("DomainEntityFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoints.
        /// </summary>
        public static string EndpointFolder {
            get {
                return ResourceManager.GetString("EndpointFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndpointTemplate.
        /// </summary>
        public static string EndpointTemplate {
            get {
                return ResourceManager.GetString("EndpointTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityDatabaseConfigurationTemplate.
        /// </summary>
        public static string EntityDatabaseConfigurationTemplate {
            get {
                return ResourceManager.GetString("EntityDatabaseConfigurationTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infrastructure.EntityFramework.
        /// </summary>
        public static string EntityFramework {
            get {
                return ResourceManager.GetString("EntityFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EntityTemplate.
        /// </summary>
        public static string EntityTemplate {
            get {
                return ResourceManager.GetString("EntityTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string InfrastructureConfigurationFolder {
            get {
                return ResourceManager.GetString("InfrastructureConfigurationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context.
        /// </summary>
        public static string InfrastructureDbContext {
            get {
                return ResourceManager.GetString("InfrastructureDbContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfrastructureDependencyInjectionBootstrapperTemplate.
        /// </summary>
        public static string InfrastructureDependencyInjectionBootstrapperTemplate {
            get {
                return ResourceManager.GetString("InfrastructureDependencyInjectionBootstrapperTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrations.
        /// </summary>
        public static string InfrastructureMigrationsFolder {
            get {
                return ResourceManager.GetString("InfrastructureMigrationsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactors.
        /// </summary>
        public static string InteractorFolder {
            get {
                return ResourceManager.GetString("InteractorFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InteractorTemplate.
        /// </summary>
        public static string InteractorTemplate {
            get {
                return ResourceManager.GetString("InteractorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MappingProfileTemplate.
        /// </summary>
        public static string MappingProfileTemplate {
            get {
                return ResourceManager.GetString("MappingProfileTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to migration.harvest.
        /// </summary>
        public static string MigrationHarvesterExtensionFile {
            get {
                return ResourceManager.GetString("MigrationHarvesterExtensionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModelTemplate.
        /// </summary>
        public static string ModelTemplate {
            get {
                return ResourceManager.GetString("ModelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presenters.
        /// </summary>
        public static string PresentersFolder {
            get {
                return ResourceManager.GetString("PresentersFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PresenterTemplate.
        /// </summary>
        public static string PresenterTemplate {
            get {
                return ResourceManager.GetString("PresenterTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queries.
        /// </summary>
        public static string Queries {
            get {
                return ResourceManager.GetString("Queries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories.
        /// </summary>
        public static string RepositoryFolder {
            get {
                return ResourceManager.GetString("RepositoryFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RepositoryTemplate.
        /// </summary>
        public static string RepositoryTemplate {
            get {
                return ResourceManager.GetString("RepositoryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestModels.
        /// </summary>
        public static string RequestModelsFolder {
            get {
                return ResourceManager.GetString("RequestModelsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestModelTemplate.
        /// </summary>
        public static string RequestModelTemplate {
            get {
                return ResourceManager.GetString("RequestModelTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liquidvisions-expanders-ca.
        /// </summary>
        public static string TemplateShortName {
            get {
                return ResourceManager.GetString("TemplateShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UseCases.
        /// </summary>
        public static string UseCases {
            get {
                return ResourceManager.GetString("UseCases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validators.
        /// </summary>
        public static string ValidatorFolder {
            get {
                return ResourceManager.GetString("ValidatorFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidatorTemplate.
        /// </summary>
        public static string ValidatorTemplate {
            get {
                return ResourceManager.GetString("ValidatorTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mappers.
        /// </summary>
        public static string ViewModelMapperFolder {
            get {
                return ResourceManager.GetString("ViewModelMapperFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModelMapperTemplate.
        /// </summary>
        public static string ViewModelMapperTemplate {
            get {
                return ResourceManager.GetString("ViewModelMapperTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModels.
        /// </summary>
        public static string ViewModelsFolder {
            get {
                return ResourceManager.GetString("ViewModelsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewModelTemplate.
        /// </summary>
        public static string ViewModelTemplate {
            get {
                return ResourceManager.GetString("ViewModelTemplate", resourceCulture);
            }
        }
    }
}
