using System.Collections.Generic;

namespace LiquidVisions.PanthaRhei.Generator.Domain.Interactors
{
    /// <summary>
    /// Represents an object that executes cli commands.
    /// </summary>
    public interface ICommandLineInteractor
    {
        /// <summary>
        /// Gets or sets a value indicating whether a cli window is created.
        /// </summary>
        bool UseWindow { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether a shell execution is used.
        /// </summary>
        bool UseShellExecution { get; set; }

        /// <summary>
        /// Gets the output stream of the command generated by the console.
        /// </summary>
        public List<string> Output { get; }

        /// <summary>
        /// Executes the command.
        /// </summary>
        /// <param name="command">the command to execute.</param>
        void Start(string command);

        /// <summary>
        /// Executes the command.
        /// </summary>
        /// <param name="command">the command to execute.</param>
        /// <param name="workingDirectory">The working directory.</param>
        void Start(string command, string workingDirectory);

        /// <summary>
        /// Executes the command.
        /// </summary>
        /// <param name="command">the command to execute.</param>
        /// <param name="silent">Determines if the command output is logged.</param>
        void Start(string command, bool silent);

        /// <summary>
        /// Executes the command.
        /// </summary>
        /// <param name="command">the command to execute.</param>
        /// <param name="workingDirectory">The working directory.</param>
        /// <param name="silent">Determines if the command output is logged.</param>
        void Start(string command, string workingDirectory, bool silent);
    }
}
