name: Pantha Rhei Pull Request

on:
  pull_request:
    branches: [ master ]

env:
  CLEANARCHITECTURE_PATH: .\Expanders\Expanders.CleanArchitecture\
  NUGET_URL: https://nuget.pkg.github.com/liquidvisions/index.json

jobs:
  
  build-PanthaRhei:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Run Unit Tests with Code Coverage
      run: dotnet test
    
  build-CleanArchitectureExpander:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        source-url: ${{ env.NUGET_URL }}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}

    - name: Restore dependencies
      run: dotnet restore ${{env.CLEANARCHITECTURE_PATH}}
    
    - name: Build
      run: dotnet build ${{env.CLEANARCHITECTURE_PATH}} --configuration Release --no-restore
    
    - name: Run Unit Tests with Code Coverage
      run: dotnet test ${{env.CLEANARCHITECTURE_PATH}}
