name: Pantha Rhei Flux - Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test /p:CollectCoverage=true  /p:CoverletOutput=../CoverageResults/ /p:MergeWith="../CoverageResults/coverage.json" /p:CoverletOutputFormat=\"cobertura,json\" -m:1
    
    - name: Codecov
      uses: codecov/codecov-action@v3.1.1
      with:
        # Repository upload token - get it from codecov.io. Required only for private repositories
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
  
  deploy:

    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: pack
      run: dotnet pack ../LiquidVisions.PanthaRhei/Generator/src/PanthaRhei.Generator.Presentation.Cli/PanthaRhei.Generator.Presentation.Cli.csproj -c Release --no-restore --no-build
    - name: push
      run: dotnet push ../LiquidVisions.PanthaRhei/Generator/src/PanthaRhei.Generator.Presentation.Cli/bin/Release/LiquidVisions.PanthaRhei.Flux.0.1.0.nupkg
