name: Update Nuget packages

on:
  workflow_dispatch:
    inputs:
      version:
        type: text
        required: true
        description: The version of the packages

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: print
      run: echo github.event.inputs.version
