name: onPullRequest

on:
  workflow_dispatch:
  pull_request:
    branches:
      - feature/*

jobs:
    build:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v2

        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 7.0.x
    
        - name: Restore dependencies
          run: dotnet restore
        
        - name: Build
          run: dotnet build --configuration Release --no-restore
        
        - name: Run Unit Tests with Code Coverage
          run: dotnet test --collect:"XPlat Code Coverage"
    
        - name: Upload to Codecov
          uses: codecov/codecov-action@v2
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            
    test:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v2

        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 7.0.x
    
        - name: Restore dependencies
          run: dotnet restore
        
        - name: Run Unit Tests with Code Coverage
          run: dotnet test --collect:"XPlat Code Coverage"
    
        - name: Upload to Codecov
          uses: codecov/codecov-action@v2
          with:
            token: ${{ secrets.CODECOV_TOKEN }}

    analyze:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v2

        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 7.0.x
    
        - name: Restore dependencies
          run: dotnet restore
        - name: Run .NET Code Analysis
          uses: dotnet/code-analysis@main
          id: code-analysis
          with:
            solution: LiquidVisions.PanthraRhei.sln
            build-breaking: true
            all-categories: all
