name: Push feature branch to remote

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master



jobs:
    push:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v2

        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 7.0.x
    
        - name: Restore dependencies
          run: dotnet restore
        
        - name: Build
          run: dotnet build --configuration Release --no-restore
        
        - name: Test
          run: dotnet test
          with:
            arguments: --no-build --configuration Release --no-restore --verbosity normal
            
        
        - name: Run .NET Code Analysis
          uses: dotnet/code-analysis@main
          id: code-analysis
          with:
            solution: LiquidVisions.PanthraRhei.sln
            build-breaking: true
            all-categories: all
