name: onPullRequest

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

jobs:
           
    test-and-upload-to-codecov:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v2

        - name: Setup .NET
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: 8.0.x
    
        - name: Restore dependencies
          run: dotnet restore
        
        - name: Run Unit Tests with Code Coverage
          run: dotnet test --collect:"XPlat Code Coverage"

        - name: Bump version
          uses: SiqiLu/dotnet-bump-version@master
          with:
            version_files: "**/src/package.version.props"
            github_token: ${{ secrets.GITHUB_TOKEN }}
