name: Pantha Rhei Push to Dev

on:
  push:
    branches: [ dev/gkoks ]

env:
  CLEANARCHITECTURE_PATH: .\Expanders\Expanders.CleanArchitecture\
  NUGET_URL: https://nuget.pkg.github.com/liquidvisions/index.json

jobs:
  
  build-PanthaRhei:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Run Unit Tests with Code Coverage
      run: dotnet test