# This is a basic workflow to help you get started with Actions
name: Publish PanthaRhei Nugets
# Controls when the workflow will run
on:
  push:
    branches: [ master ]

env:
 PACKAGE_FOLDER: D:\a\LiquidVisions.PanthaRhei\LiquidVisions.PanthaRhei\src\package\

jobs:
  push-to-master:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Run Unit Tests with Code Coverage
      run: dotnet test --collect:"XPlat Code Coverage"

    - name: Upload to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Pack PanthaRhei.Presentation.Cli
      run: |  
        cd src/Presentation.Cli/
        dotnet pack -c Release -o D:\a\LiquidVisions.PanthaRhei\LiquidVisions.PanthaRhei\src\package\
        
    - name: Pack PanthaRhei.Domain.Core
      run: |  
        cd src/Domain/
        dotnet pack -c Release -o D:\a\LiquidVisions.PanthaRhei\LiquidVisions.PanthaRhei\src\package\

    - name: Pack PanthaRhei.Tests
      run: |  
        cd tests/PanthaRhei.Tests/
        dotnet pack -c Release -o D:\a\LiquidVisions.PanthaRhei\LiquidVisions.PanthaRhei\src\package\ -IncludeReferencedProjects
        

    - name: Push generated package to GitHub registry
      run: dotnet nuget push D:\a\LiquidVisions.PanthaRhei\LiquidVisions.PanthaRhei\src\package\*.nupkg --skip-duplicate --no-symbols --source https://nuget.pkg.github.com/liquidvisions/index.json --api-key ${{secrets.GITHUB_TOKEN}}
