# This is a basic workflow to help you get started with Actions
name: Publish PanthaRhei Nugets
# Controls when the workflow will run
on:
  push:
    branches: [ gkoks/dev ]

jobs:
  publish-nuget:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build solution and generate NuGet package
      run: |  
        cd src/Presentation.Cli/
        dotnet pack -c Release -o ./packages
        cd src/Domain/
        dotnet pack -c Release -o ./packages --source https://nuget.pkg.github.com/liquidvisions/index.json --api-key ${{secrets.GITHUB_TOKEN}}

    - name: Push generated package to GitHub registry
      run: dotnet nuget push ./packages/*.nupkg --skip-duplicate --no-symbols true
