name: Debug GitHub Context

on: [push]

jobs:
  push-nuget-packages:

    runs-on: windows-latest

    steps:
    
    - name: Trigger Template NuGet Package Update Event
      env:
        TOKEN: ${{ secrets.DISPATCH_TOKEN }}
      run: |
        response=$(curl -L -s -w "%{http_code}" \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $TOKEN" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/LiquidVisions/LiquidVisions.PanthaRhei.Templates/dispatches \
        -d '{"event_type":"nuget-package-update","client_payload":{"unit":false,"integration":true}}' -o response_body)
        
        status_code=$(tail -n1 <<< "$response")
        response_body=$(<response_body)
        
        if [ "$status_code" -ne 200 ]; then
          echo "Request failed with status code $status_code"
          echo "Response body: $response_body"
          exit 1
        else
          echo "Request succeeded with status code $status_code"
          echo "Response body: $response_body"
        fi
      shell: bash

