name: Debug GitHub Context

on: [push]

jobs:
  push-nuget-packages:

    runs-on: windows-latest

    steps:
    
    - name: Trigger NuGet Package Update Event
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          pwsh -Command "
          Invoke-RestMethod -Method Post -Uri 'https://api.github.com/repos/LiquidVisions/LiquidVisions.PanthaRhei.Templates/dispatches' -Headers @{
              Accept = 'application/vnd.github.everest-preview+json'
              Authorization = 'token $env:GITHUB_TOKEN'
          } -Body (@{ event_type = 'nuget-package-update' } | ConvertTo-Json)
          "
