name: test

on:
  workflow_dispatch:

jobs:
  push-nuget-packages:

    runs-on: ubuntu-latest

    steps:
   
      - name: Trigger blog build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: <username>/<repository>
          event-type: update
