name: Push nuget packages

on:
  workflow_dispatch:

jobs:
  push-nuget-packages:

    runs-on: ubuntu-latest

    steps:
   
    - name: Trigger Template NuGet Package Update Event
      env:
        TOKEN: ${{ secrets.REPOSITORY_DISPATCH_EVENT }}
      run: |
        response=$(curl -s -w "%{http_code}" \
        -o response_body.txt \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer $TOKEN" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/LiquidVisions/LiquidVisions.PanthaRhei.Templates/dispatches \
        -d '{"event_type":"nuget-package-update","client_payload":{"unit":false,"integration":true}}')
    
        status_code=$(tail -n1 response_body.txt)
        response_body=$(cat response_body.txt)
    
        if [ "$status_code" -ne 200 ]; then
          echo "Request failed with status code $status_code"
          echo "Response body: $response_body"
          exit 1
        else
          echo "Request succeeded with status code $status_code"
          echo "Response body: $response_body"
        fi
