name: test

on:
  workflow_dispatch:

jobs:
  push-nuget-packages:

    runs-on: ubuntu-latest

    steps:
   
      - name: Trigger blog build
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPOSITORY_DISPATCH_EVENT }}
          repository: LiquidVisions/LiquidVisions.PanthaRhei.Templates
          event-type: update
